### PR TITLE
Fixed hook_help() parameters.

### PR DESCRIPTION
**Pull request by joachim-n**
Wrong params for hook_help -- crashes Drupal on module install.

### CODE REVIEW

**Comment by dakala** [comment]
@joachim-n , sorry about this. I;ve just renamed the module to profile. Will apply this patch manually.

**Comment by dakala** [comment]
Is it okay to continue as is? i.e. with the module name changed? Thanks! Strange feeling, having to work with someone on this at last :-)

**Comment by joachim-n** [comment]
Probably won't merge cleanly as the function name is changed. It's a single-line patch anyway. Should be simple to fix the merge, or I can redo the branch, up to you.

**Comment by dakala** [comment]
I've just pushed the change.

**Comment by dakala** [comment]
Now, my hook_help() no longer works. \Drupal\Core\Routing\RouteMatchInterface is an undefined class. I'm working off the alpha-12 release.  Most likely  you've got the latest from HEAD, right?

**Comment by joachim-n** [comment]
Yes, I'm on D8 HEAD.

**Pull request closed without merging**
