### PR TITLE
D8beta4 tests fix

### PR DESCRIPTION
**Pull request by GoZOo**
Many fixes to make tests or module work with new core updates.

### CODE REVIEW

**Comment by GoZOo** [comment]
ProfileAttachTest pass tests except checking profile field data on user page :

```
Fail      Other      ProfileAttachTest  117 Drupal\profile\Tests\ProfileAttachT
    Field value found on user account page.
```

**Comment by GoZOo** [comment]
With last commit, ProfileAttachTest pass tests.

**Comment by GoZOo** [comment]
Adding some fix to allow create/edit/delete profiles.

I choose to activate profiles at creation if user hasn't 'administer profiles' permission. It makes no sense to let user create inactive profile. But if profile is inactive, he can't activate it back.

**Comment by GoZOo** [comment]
I don't find any occurences about private field (tested on ProfileFieldAccessTest.php). So this test still have failed.

All others success. One have still 2 exceptions (ProfileTypeCRUDTest) but don't find fix yet.

Still have few work like taking care of creation limitation by bundle or adding link to create profile on user page.
Otherwise, module works :)

**Comment by GoZOo** [comment]
Juste update core... and every tests fails...
I check what's wrong

**Comment by dakala** [comment]
Merging this in. About time to catch up on what's going on. Latest core update broke my dev, have to clean install :-)

**Pull request merged**
